### ISSUE TITLE
Anomaly found while change of pace

### ISSUE THREAD

**Issue by Toucouleur66** [ankane/AnomalyDetection.rb#2]
Hi there,

thanks for your work. We have been using on many GPS tracks your Anomaly Detection to sort and filter all bad position reported by incorrect GPS fix.

It works well still I'm trying to figure how I should handle such case. So far we are checking speed to detect anomaly but we would have the same issue by checking distance or straight GPS latitude/longitude. I attached a graph to provide a sample of data where I got some anomaly detection found while it's a normal behavior and expected data.

How should we resolve this?

<img width="1413" alt="Capture d’écran 2022-09-25 à 06 08 31" src="https://user-images.githubusercontent.com/75485458/192127970-5fa4fb03-1d4f-44fa-aae9-b8e34b9f7e25.png">

**Comment by ankane** [comment]
Hey @Toucouleur66, you'll probably want to use a different approach / library for this ([one possible approach](https://jeffreyearly.com/smoothing-and-interpolating-noisy-gps-data/)). If you find something that works well, I'd be curious to hear the details.

**Comment by Toucouleur66** [comment]
Seems to be very interesting thanks for the tip
